// src/routes/adminRoute.ts
import { Router } from "express";
import * as adminController from "../controllers/adminController";
import * as homeController from "../controllers/homeController";
import adminAuthMiddleware from "../middlewares/adminAuthMiddleware";
import {
	adminUpdateProfileValidationRules,
	updatePasswordValidationRules,
	createSubAdminValidationRules,
	updateSubAdminValidationRules,
	createSubscriptionPlanValidationRules,
	updateSubscriptionPlanValidationRules,
	validateKYCNotification,
	validatePaymentGateway,
	createStoreValidation,
	updateStoreValidation,
	addProductValidation,
	updateProductValidation,
	auctionProductValidation,
	createAdvertValidation,
	updateAdvertValidation,
	postJobValidationRules,
	validate,
	updateAuctionProductValidation,
	paginationQueryParamsValidation,
	productChargeValidation,
	ServiceCategoryValidation,
	ServiceIdValidation,
	ServiceSubCategoryValidation,
	CreateServiceAttributeValidation,
	AddServiceAttributeOptionsValidation,
	AddServiceCategoryToAttributeValidation,
	RemoveServiceCategoryFromAttributeValidation,
	validateUUIDParam,
	addAliexpressProductValidation,
} from "../utils/validations"; // Import the service
import checkPermission from "../middlewares/checkPermissionMiddleware";
import { PERMISSIONS } from "../utils/permissions";
import {
	getAdminNotifications,
	markAdminNotificationAsRead,
} from "../controllers/adminController";

const adminRoutes = Router();

// User routes
adminRoutes.get("/logout", adminAuthMiddleware, adminController.logout);
adminRoutes.put(
	"/profile/update",
	adminAuthMiddleware,
	adminUpdateProfileValidationRules(),
	validate,
	checkPermission("update-profile"),
	adminController.updateProfile,
);
adminRoutes.put(
	"/profile/update/password",
	adminAuthMiddleware,
	updatePasswordValidationRules(),
	validate,
	checkPermission("update-password"),
	adminController.updatePassword,
);

// Sub Admin
adminRoutes.get(
	"/sub-admins",
	adminAuthMiddleware,
	checkPermission("view-subadmin"),
	adminController.subAdmins,
);
adminRoutes.post(
	"/sub-admin/create",
	adminAuthMiddleware,
	createSubAdminValidationRules(),
	validate,
	checkPermission("create-subadmin"),
	adminController.createSubAdmin,
);
adminRoutes.put(
	"/sub-admin/update",
	adminAuthMiddleware,
	updateSubAdminValidationRules(),
	validate,
	checkPermission("update-subadmin"),
	adminController.updateSubAdmin,
);
adminRoutes.patch(
	"/sub-admin/status",
	adminAuthMiddleware,
	checkPermission("activateanddeactivate-subadmin"),
	adminController.deactivateOrActivateSubAdmin,
);
adminRoutes.delete(
	"/sub-admin/delete",
	adminAuthMiddleware,
	checkPermission("delete-subadmin"),
	adminController.deleteSubAdmin,
);
adminRoutes.post(
	"/sub-admin/resend-login",
	adminAuthMiddleware,
	checkPermission("resendlogindetails-subadmin"),
	adminController.resendLoginDetailsSubAdmin,
);

// Role
adminRoutes.get(
	"/roles",
	adminAuthMiddleware,
	checkPermission("view-role"),
	adminController.getRoles,
);
adminRoutes.post(
	"/role/create",
	adminAuthMiddleware,
	checkPermission("create-role"),
	adminController.createRole,
);
adminRoutes.put(
	"/role/update",
	adminAuthMiddleware,
	checkPermission("update-role"),
	adminController.updateRole,
);
adminRoutes.get(
	"/role/view/permissions",
	adminAuthMiddleware,
	checkPermission("view-role-permissions"),
	adminController.viewRolePermissions,
);
adminRoutes.post(
	"/role/assign/permission",
	adminAuthMiddleware,
	checkPermission("assign-role-permissions"),
	adminController.assignPermissionToRole,
);
adminRoutes.delete(
	"/role/delete/permission",
	adminAuthMiddleware,
	checkPermission("delete-role-permissions"),
	adminController.deletePermissionFromRole,
);

// Permission
adminRoutes.get(
	"/permissions",
	adminAuthMiddleware,
	checkPermission("view-permission"),
	adminController.getPermissions,
);
adminRoutes.get(
	"/permissions/me",
	adminAuthMiddleware,
	adminController.getMyPermissions,
);

// Subscription Plan
adminRoutes.get(
	"/subscription/plans",
	adminAuthMiddleware,
	adminController.getAllSubscriptionPlans,
);
adminRoutes.post(
	"/subscription/plan/create",
	adminAuthMiddleware,
	createSubscriptionPlanValidationRules(),
	validate,
	adminController.createSubscriptionPlan,
);
adminRoutes.put(
	"/subscription/plan/update",
	adminAuthMiddleware,
	updateSubscriptionPlanValidationRules(),
	validate,
	adminController.updateSubscriptionPlan,
);
adminRoutes.delete(
	"/subscription/plan/delete",
	adminAuthMiddleware,
	adminController.deleteSubscriptionPlan,
);

// Create a category
adminRoutes.post(
	"/categories",
	adminAuthMiddleware,
	adminController.createCategory,
);
// Update a category
adminRoutes.put(
	"/categories",
	adminAuthMiddleware,
	adminController.updateCategory,
);
// Delete a category
adminRoutes.delete(
	"/categories",
	adminAuthMiddleware,
	adminController.deleteCategory,
);
// Fetch all categories
adminRoutes.get(
	"/categories",
	adminAuthMiddleware,
	adminController.getAllCategories,
);
adminRoutes.get(
	"/categories/sub/categories",
	adminAuthMiddleware,
	adminController.getCategoriesWithSubCategories,
);

adminRoutes.post(
	"/sub/categories",
	adminAuthMiddleware,
	adminController.createSubCategory,
);
adminRoutes.put(
	"/sub/categories",
	adminAuthMiddleware,
	adminController.updateSubCategory,
);
adminRoutes.delete(
	"/sub/categories",
	adminAuthMiddleware,
	adminController.deleteSubCategory,
);
adminRoutes.get(
	"/sub/categories",
	adminAuthMiddleware,
	adminController.getAllSubCategories,
);

// KYC
adminRoutes.get(
	"/kyc",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_KYC),
	adminController.getAllKYC,
);
adminRoutes.post(
	"/kyc/approve-reject",
	adminAuthMiddleware,
	validateKYCNotification(),
	validate,
	checkPermission(PERMISSIONS.MANAGE_KYC),
	adminController.approveOrRejectKYC,
);

// Payment Gateway
adminRoutes.post(
	"/payment-gateway",
	adminAuthMiddleware,
	validatePaymentGateway(),
	validate,
	adminController.createPaymentGateway,
);
adminRoutes.put(
	"/payment-gateway",
	adminAuthMiddleware,
	validatePaymentGateway(),
	validate,
	adminController.updatePaymentGateway,
);
adminRoutes.delete(
	"/payment-gateway",
	adminAuthMiddleware,
	adminController.deletePaymentGateway,
);
adminRoutes.get(
	"/payment-gateways",
	adminAuthMiddleware,
	adminController.getAllPaymentGateways,
);
adminRoutes.get(
	"/payment-gateway",
	adminAuthMiddleware,
	adminController.paymentGateway,
);
adminRoutes.patch(
	"/payment-gateways/status",
	adminAuthMiddleware,
	adminController.setPaymentGatewayActive,
);

// Currency
adminRoutes.post("/currency", adminAuthMiddleware, adminController.addCurrency);
adminRoutes.put(
	"/currency",
	adminAuthMiddleware,
	adminController.updateCurrency,
);
adminRoutes.delete(
	"/currency",
	adminAuthMiddleware,
	adminController.deleteCurrency,
);
adminRoutes.get(
	"/currencies",
	adminAuthMiddleware,
	adminController.getAllCurrencies,
);

// users
adminRoutes.get(
	"/customers",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_CUSTOMERS),
	adminController.getAllCustomers,
);
adminRoutes.get(
	"/vendors",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_VENDORS),
	adminController.getAllVendors,
);
adminRoutes.get(
	"/user/details",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_CUSTOMERS),
	adminController.viewUser,
);
adminRoutes.patch(
	"/toggle/user/status",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_CUSTOMERS),
	adminController.toggleUserStatus,
);

// Store
adminRoutes.get(
	"/store",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_STORES),
	adminController.getStore,
);
adminRoutes.post(
	"/store",
	adminAuthMiddleware,
	createStoreValidation(),
	validate,
	checkPermission(PERMISSIONS.MANAGE_STORES),
	adminController.createStore,
);
adminRoutes.put(
	"/store",
	adminAuthMiddleware,
	updateStoreValidation(),
	validate,
	checkPermission(PERMISSIONS.MANAGE_STORES),
	adminController.updateStore,
);
adminRoutes.delete(
	"/store",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_STORES),
	adminController.deleteStore,
);

// Product
adminRoutes.get(
	"/products",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_PRODUCTS),
	adminController.fetchProducts,
);
adminRoutes.post(
	"/products",
	adminAuthMiddleware,
	addProductValidation(),
	validate,
	checkPermission(PERMISSIONS.MANAGE_PRODUCTS),
	adminController.createProduct,
);
adminRoutes.put(
	"/products",
	adminAuthMiddleware,
	updateProductValidation(),
	validate,
	checkPermission(PERMISSIONS.MANAGE_PRODUCTS),
	adminController.updateProduct,
);
adminRoutes.delete(
	"/products",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_PRODUCTS),
	adminController.deleteProduct,
);
adminRoutes.get(
	"/product",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_PRODUCTS),
	adminController.viewProduct,
);
adminRoutes.patch(
	"/products/move-to-draft",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_PRODUCTS),
	adminController.moveToDraft,
);
adminRoutes.patch(
	"/products/change-status",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_PRODUCTS),
	adminController.changeProductStatus,
);

// Auction Product
adminRoutes.get(
	"/auction/products",
	adminAuthMiddleware,
	adminController.fetchAuctionProducts,
);
adminRoutes.post(
	"/auction/products",
	adminAuthMiddleware,
	auctionProductValidation(),
	validate,
	adminController.createAuctionProduct,
);
adminRoutes.put(
	"/auction/products",
	adminAuthMiddleware,
	updateAuctionProductValidation(),
	validate,
	adminController.updateAuctionProduct,
);
adminRoutes.delete(
	"/auction/products",
	adminAuthMiddleware,
	adminController.deleteAuctionProduct,
);
adminRoutes.patch(
	"/auction/products",
	adminAuthMiddleware,
	adminController.cancelAuctionProduct,
);
adminRoutes.get(
	"/auction/product",
	adminAuthMiddleware,
	adminController.viewAuctionProduct,
);
adminRoutes.get(
	"/auction/product/bidders",
	adminAuthMiddleware,
	adminController.getAllBidsByAuctionProductId,
);

// Orders
adminRoutes.get(
	"/order/items",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_ORDERS),
	adminController.getOrderItems,
);
adminRoutes.get(
	"/order/item",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_ORDERS),
	adminController.viewOrderItem,
);

adminRoutes.get(
	"/order/dropship/items",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_ORDERS),
	adminController.getDropshipedOrderItemDetails,
);

adminRoutes.get(
	"/order/dropship/tracking/info",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_ORDERS),
	adminController.getDropshipOrderTrackingInfo,
);

adminRoutes.get(
	"/order/item/details",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_ORDERS),
	adminController.getOrderItemsInfo,
);
adminRoutes.post(
	"/order/item/update/status",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_ORDERS),
	adminController.updateOrderStatus,
);

//General Store | Product | Auction Products | Adverts
adminRoutes.get(
	"/general/stores",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_STORES),
	adminController.getGeneralStores,
);
adminRoutes.get(
	"/general/store/view",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_STORES),
	adminController.viewGeneralStore,
);
adminRoutes.get(
	"/general/products",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_PRODUCTS),
	adminController.getGeneralProducts,
);
adminRoutes.get(
	"/general/product/view",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_PRODUCTS),
	adminController.viewGeneralProduct,
);
adminRoutes.delete(
	"/general/product/delete",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_PRODUCTS),
	adminController.deleteGeneralProduct,
);
adminRoutes.put(
	"/general/product/unpublished",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_PRODUCTS),
	adminController.unpublishProduct,
);
adminRoutes.put(
	"/general/product/publish",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_PRODUCTS),
	adminController.publishProduct,
);
adminRoutes.get(
	"/general/auction/products",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_PRODUCTS),
	adminController.getGeneralAuctionProducts,
);
adminRoutes.get(
	"/general/auction/product/view",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_PRODUCTS),
	adminController.viewGeneralAuctionProduct,
);
adminRoutes.delete(
	"/general/auction/product/delete",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_PRODUCTS),
	adminController.deleteGeneralAuctionProduct,
);
adminRoutes.get(
	"/general/auction/product/bidders",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_PRODUCTS),
	adminController.getAllBiddersByAuctionProductId,
);
adminRoutes.get(
	"/general/orders",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_ORDERS),
	adminController.getAllGeneralOrders,
);
adminRoutes.get(
	"/general/order/items",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_ORDERS),
	adminController.getAllGeneralOrderItems,
);
adminRoutes.get(
	"/general/order/payment",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_ORDERS),
	adminController.getGeneralPaymentDetails,
);
adminRoutes.get(
	"/general/adverts",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_ADVERTS),
	adminController.getGeneralAdverts,
);
adminRoutes.get(
	"/general/advert/view",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_ADVERTS),
	adminController.viewGeneralAdvert,
);

// Subscribers
adminRoutes.get(
	"/subscribers",
	adminAuthMiddleware,
	adminController.getAllSubscribers,
);

// Transactions
adminRoutes.get(
	"/transactions",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_TRANSACTIONS),
	adminController.getTransactionsForAdmin,
);

// Adverts
adminRoutes.get(
	"/active/products",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_ADVERTS),
	adminController.activeProducts,
);
adminRoutes.post(
	"/adverts",
	createAdvertValidation(),
	validate,
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_ADVERTS),
	adminController.createAdvert,
);
adminRoutes.put(
	"/adverts",
	updateAdvertValidation(),
	validate,
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_ADVERTS),
	adminController.updateAdvert,
);
adminRoutes.get(
	"/adverts",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_ADVERTS),
	adminController.getAdverts,
);
adminRoutes.get(
	"/advert",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_ADVERTS),
	adminController.viewAdvert,
);
adminRoutes.delete(
	"/adverts",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_ADVERTS),
	adminController.deleteAdvert,
);
adminRoutes.post(
	"/approved-reject/advert",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_ADVERTS),
	adminController.approveOrRejectAdvert,
);

// Testimonial
adminRoutes.post(
	"/testimonial",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_PAGES),
	adminController.createTestimonial,
);
adminRoutes.put(
	"/testimonial",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_PAGES),
	adminController.updateTestimonial,
);
adminRoutes.get(
	"/testimonials",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_PAGES),
	adminController.getAllTestimonials,
);
adminRoutes.get(
	"/testimonial",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_PAGES),
	adminController.getTestimonial,
);
adminRoutes.delete(
	"/testimonial",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_PAGES),
	adminController.deleteTestimonial,
);

// FAQ Category Routes
adminRoutes.post(
	"/faq/category",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_PAGES),
	adminController.createFaqCategory,
);
adminRoutes.get(
	"/faq/categories",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_PAGES),
	adminController.getAllFaqCategories,
);
adminRoutes.get(
	"/faq/category",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_PAGES),
	adminController.getFaqCategory,
);
adminRoutes.put(
	"/faq/category",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_PAGES),
	adminController.updateFaqCategory,
);
adminRoutes.delete(
	"/faq/category",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_PAGES),
	adminController.deleteFaqCategory,
);

// FAQ Routes
adminRoutes.post(
	"/faq",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_PAGES),
	adminController.createFaq,
);
adminRoutes.get(
	"/faqs",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_PAGES),
	adminController.getAllFaqs,
);
adminRoutes.get(
	"/faq",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_PAGES),
	adminController.getFaq,
);
adminRoutes.put(
	"/faq",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_PAGES),
	adminController.updateFaq,
);
adminRoutes.delete(
	"/faq",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_PAGES),
	adminController.deleteFaq,
);

// Contact Us Form
adminRoutes.get(
	"/contact/us/forms",
	adminAuthMiddleware,
	adminController.getAllContacts,
);
adminRoutes.get(
	"/contact/us/form",
	adminAuthMiddleware,
	adminController.getContactById,
);
adminRoutes.delete(
	"/contact/us/form",
	adminAuthMiddleware,
	adminController.deleteContactById,
);

// Job
adminRoutes.post(
	"/job/post",
	adminAuthMiddleware,
	postJobValidationRules(),
	validate,
	checkPermission(PERMISSIONS.MANAGE_JOBS),
	adminController.postJob,
);
adminRoutes.put(
	"/job/update",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_JOBS),
	adminController.updateJob,
);
adminRoutes.get(
	"/jobs",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_JOBS),
	adminController.getJobs,
);
adminRoutes.get(
	"/job",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_JOBS),
	adminController.getJobById,
);
adminRoutes.patch(
	"/job/close",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_JOBS),
	adminController.closeJob,
);
adminRoutes.delete(
	"/job/delete",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_JOBS),
	adminController.deleteJob,
);
adminRoutes.post(
	"/job/repost",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_JOBS),
	adminController.repostJob,
);
adminRoutes.get(
	"/job/applicants",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_JOBS),
	adminController.getJobApplicants,
);
adminRoutes.get(
	"/job/view/applicant",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_JOBS),
	adminController.viewApplicant,
);
adminRoutes.get(
	"/job/download/applicant/resume",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_JOBS),
	adminController.downloadApplicantResume,
);

// Withdrawals
adminRoutes.post(
	"/withdrawal/update/status",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_WITHDRAWALS),
	adminController.updateWithdrawalStatus,
);
adminRoutes.get(
	"/withdrawals",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_WITHDRAWALS),
	adminController.getWithdrawals,
);
adminRoutes.get(
	"/withdrawal",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_WITHDRAWALS),
	adminController.getWithdrawalById,
);

// BANNER Routes
adminRoutes.post(
	"/banner",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_PAGES),
	adminController.createBanner,
);
adminRoutes.get(
	"/banners",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_PAGES),
	adminController.getAllBanners,
);
adminRoutes.get(
	"/banner",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.VIEW_PAGES),
	adminController.getBanner,
);
adminRoutes.put(
	"/banner",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_PAGES),
	adminController.updateBanner,
);
adminRoutes.delete(
	"/banner",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_PAGES),
	adminController.deleteBanner,
);

// Admin notifications
adminRoutes.get(
	"/notifications",
	adminAuthMiddleware,
	paginationQueryParamsValidation(),
	validate,
	getAdminNotifications,
);
adminRoutes.patch(
	"/notifications/:id/read",
	adminAuthMiddleware,
	markAdminNotificationAsRead,
);

adminRoutes.post(
	"/product/charges",
	productChargeValidation(),
	validate,
	adminAuthMiddleware,
	adminController.createProductCharge,
);

adminRoutes.put(
	"/product/charges/:id",
	productChargeValidation(),
	validate,
	adminAuthMiddleware,
	adminController.updateProductCharge,
);

adminRoutes.get(
	"/product/charges",
	adminAuthMiddleware,
	adminController.getAllProductCharges,
);

adminRoutes.delete(
	"/product/charges/:id",
	adminAuthMiddleware,
	adminController.deleteProductCharge,
);

adminRoutes.patch(
	"/product/charges/:id/status/activate",
	adminAuthMiddleware,
	adminController.markProductChargeAsActive,
);

adminRoutes.patch(
	"/product/charges/:id/status/deactivate",
	adminAuthMiddleware,
	adminController.markProductChargeAsInactive,
);

adminRoutes.post(
	"/service/categories",
	adminAuthMiddleware,
	ServiceCategoryValidation(),
	validate,
	checkPermission(PERMISSIONS.MANAGE_SERVICES),
	adminController.createServiceCategory,
);

adminRoutes.put(
	"/service/categories/:id",
	adminAuthMiddleware,
	ServiceIdValidation(),
	ServiceCategoryValidation(),
	validate,
	checkPermission(PERMISSIONS.MANAGE_SERVICES),
	adminController.updateServiceCategory,
);

adminRoutes.get(
	"/service/categories",
	adminAuthMiddleware,
	paginationQueryParamsValidation(),
	validate,
	checkPermission(PERMISSIONS.VIEW_SERVICES),
	adminController.getAllServiceCategories,
);

adminRoutes.delete(
	"/service/categories/:id",
	adminAuthMiddleware,
	ServiceIdValidation(),
	validate,
	checkPermission(PERMISSIONS.MANAGE_SERVICES),
	adminController.deleteServiceCategory,
);

adminRoutes.post(
	"/service/subcategories",
	adminAuthMiddleware,
	ServiceSubCategoryValidation(),
	validate,
	checkPermission(PERMISSIONS.MANAGE_SERVICES),
	adminController.createServiceSubCategory,
);

adminRoutes.put(
	"/service/subcategories/:id",
	adminAuthMiddleware,
	ServiceIdValidation(),
	ServiceSubCategoryValidation(),
	validate,
	checkPermission(PERMISSIONS.MANAGE_SERVICES),
	adminController.updateServiceSubCategory,
);

adminRoutes.get(
	"/service/subcategories/:id",
	adminAuthMiddleware,
	ServiceIdValidation(),
	paginationQueryParamsValidation(),
	validate,
	checkPermission(PERMISSIONS.VIEW_SERVICES),
	adminController.getAllServiceSubCategories,
);

adminRoutes.delete(
	"/service/subcategories/:id",
	adminAuthMiddleware,
	ServiceIdValidation(),
	validate,
	checkPermission(PERMISSIONS.MANAGE_SERVICES),
	adminController.deleteServiceSubCategory,
);

adminRoutes.post(
	"/service/attributes",
	adminAuthMiddleware,
	CreateServiceAttributeValidation(),
	validate,
	checkPermission(PERMISSIONS.MANAGE_SERVICES),
	adminController.createServiceAttribute,
);

adminRoutes.delete(
	"/service/attributes/:id",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_SERVICES),
	adminController.deleteServiceAttribute,
);

adminRoutes.post(
	"/service/attributes/:attributeId/options",
	adminAuthMiddleware,
	AddServiceAttributeOptionsValidation(),
	validate,
	checkPermission(PERMISSIONS.MANAGE_SERVICES),
	adminController.addAttributeOptions,
);

adminRoutes.get(
	"/service/attributes",
	adminAuthMiddleware,
	paginationQueryParamsValidation(),
	validate,
	checkPermission(PERMISSIONS.VIEW_SERVICES),
	adminController.getAllServiceAttributes,
);

adminRoutes.delete(
	"/service/attributes/options/:optionId",
	adminAuthMiddleware,
	checkPermission(PERMISSIONS.MANAGE_SERVICES),
	adminController.deleteAttributeOption,
);

adminRoutes.post(
	"/service/categories/:categoryId/attributes",
	adminAuthMiddleware,
	AddServiceCategoryToAttributeValidation(),
	validate,
	checkPermission(PERMISSIONS.MANAGE_SERVICES),
	adminController.addAttributeToServiceCategory,
);

adminRoutes.get(
	"/service/categories/:categoryId/attributes",
	adminAuthMiddleware,
	paginationQueryParamsValidation(),
	validate,
	homeController.getAttributesForServiceCategory,
);

adminRoutes.delete(
	"/service/categories/:categoryId/attributes",
	adminAuthMiddleware,
	RemoveServiceCategoryFromAttributeValidation(),
	validate,
	adminController.removeAttributeFromServiceCategory,
);

adminRoutes.post(
	"/service/:serviceId/suspend",
	validateUUIDParam("serviceId"),
	validate,
	adminAuthMiddleware,
	adminController.suspendService,
);

adminRoutes.post(
	"/service/:serviceId/activate",
	validateUUIDParam("serviceId"),
	validate,
	adminAuthMiddleware,
	adminController.activateService,
);

adminRoutes.get(
	"/services",
	adminAuthMiddleware,
	paginationQueryParamsValidation(),
	validate,
	adminController.getAllServices,
);

adminRoutes.get(
	"/services/:serviceId",
	adminAuthMiddleware,
	validateUUIDParam("serviceId"),
	validate,
	adminController.getServiceById,
);

adminRoutes.get(
	"/aliexpress/categories",
	adminAuthMiddleware,
	adminController.getAliExpressCategories,
);

adminRoutes.get(
	"/aliexpress/products",
	adminAuthMiddleware,
	adminController.getAliExpressProducts,
);

adminRoutes.get(
	"/aliexpress/products/:productId/details",
	adminAuthMiddleware,
	adminController.getAliExpressProductDetails,
);

adminRoutes.post(
	"/aliexpress/products/import",
	adminAuthMiddleware,
	addAliexpressProductValidation(),
	validate,
	adminController.addAliexpressProductToInventory,
);

adminRoutes.get(
	"/aliexpress/credentials/status",
	adminAuthMiddleware,
	adminController.getAliExpressDropshipCredsStatus,
);

// Product offer routes
adminRoutes.get(
	"/offers",
	adminAuthMiddleware,
	adminController.getAllOffers,
);

adminRoutes.put(
	"/offers/:offerId",
	adminAuthMiddleware,
	adminController.respondToOffer,
);

export default adminRoutes; // Export the router
